<a href="https://colab.research.google.com/github/anirudh0345/ML_LAB/blob/main/KNearest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn.datasets import load_iris
iris = load_iris()
iris
type(iris)
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [ ]:
x = iris.data
y = iris.target

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
classifier = KNeighborsClassifier(n_neighbors=30)
classifier.fit(x_train, y_train)

#To make predictions on our test data
y_pred=classifier.predict(x_test)



In [ ]:

for x_t in x_test:
  d =[ ]
  for xe_t in x_train:
    distance = np.linalg.norm(x_t - xe_t)
    d.append(distance)
    d.sort()
  print(d[:5])
  print( )

[0.34641016151377513, 0.374165738677394, 0.3741657386773942, 0.38729833462074154, 0.38729833462074154]

[0.38729833462074165, 0.5196152422706634, 0.529150262212918, 0.5385164807134499, 0.5477225575051655]

[0.43588989435406733, 0.5567764362830021, 0.8660254037844384, 0.877496438739212, 0.9273618495495707]

[0.5477225575051664, 0.8062257748298545, 0.818535277187245, 0.8831760866327846, 0.9643650760992953]

[0.33166247903553986, 0.3872983346207414, 0.46904157598234314, 0.5099019513592783, 0.519615242270663]

[0.14142135623730964, 0.14142135623730995, 0.3000000000000001, 0.31622776601683783, 0.38729833462074165]

[0.14142135623730964, 0.14142135623730995, 0.17320508075688762, 0.20000000000000034, 0.20000000000000034]

[0.31622776601683755, 0.3741657386773941, 0.3741657386773946, 0.42426406871192845, 0.4242640687119287]

[0.17320508075688815, 0.26457513110645914, 0.30000000000000016, 0.33166247903553986, 0.33166247903554]

[0.34641016151377546, 0.3872983346207415, 0.42426406871192895, 0.43

In [ ]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_pred))
print('Accuracy Metrics')
print(classification_report(y_test,y_pred))

Confusion Matrix
[[13  0  0]
 [ 0 11  1]
 [ 0  7 13]]
Accuracy Metrics
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.61      0.92      0.73        12
           2       0.93      0.65      0.76        20

    accuracy                           0.82        45
   macro avg       0.85      0.86      0.83        45
weighted avg       0.86      0.82      0.82        45

